### PR TITLE
Add link to node-livy-client

### PR DESCRIPTION
**Pull request by LaurenSpiegel**
Hi,

I created a livy client in NodeJS and published to npm. I reference it here in case it is helpful to others.  Thanks!

### CODE REVIEW

**Comment by ajbozarth** [comment]
Thank you for your contribution to the Livy community but the Livy Docs should be for Livy itself and not 3rd party code. I would suggest sharing your link on the user mailing list in order to spread word. I took a look at your code though and it's a nice Livy client. @jerryshao and @lresende would you agree, or am I being too rigid?

**Comment by jerryshao** [comment]
I think we can have a section in website to introduce third-party libraries. I'm not sure if it against Apache's policy.

**Comment by LaurenSpiegel** [comment]
Thanks, @ajbozarth and @jerryshao. I wasn't sure if I added it to the best place on the website. Maybe a separate page with ecosystem projects make sense?  Spark itself has one -- https://spark.apache.org/third-party-projects.html
Livy should be added to that page 😄

**Comment by ajbozarth** [comment]
Your right we should probably be on that page. And I'm in support of creating a new page to support 3rd party Livy projects like this one.

**Pull request closed without merging**
