### PR TITLE
[Minor] Updated Contribution Section to include PR Naming Practices

### PR DESCRIPTION
**Pull request by ajbozarth**
Practices copied from Bahir Contributing page and match Spark practices

### CODE REVIEW

**Comment by ajbozarth** [comment]
@lresende @jerryshao

**Comment by jerryshao** [comment]
I think we follow the pattern of "LIVY-xxx." not "[LIVY-xxx]", if you want to change to "[LIVY-xxx]" you should also update merge_livy_pr.py.

**Comment by ajbozarth** [comment]
@jerryshao would you mind updating the script? I'm a bit rusty on my regex and you could probably update it quicker

**Comment by jerryshao** [comment]
I'm not sure why do we have to change to "[LIVY-xxx]", we've used "LIVY-xxx." for a long time, is it required by ASF?

**Comment by ajbozarth** [comment]
I believe its Apache standard, is that correct @lresende ?

**Comment by jerryshao** [comment]
Do we need to manually run publish.sh to make it live?

**Comment by ajbozarth** [comment]
I believe that is correct

**Comment by jerryshao** [comment]
Looks like jekyll is required, I don't install it locally, needs time to figure out.

@lresende would you please help to update asf-site branch, thanks a lot!

**Comment by lresende** [comment]
I don't have strong feelings to [LIVY-xxx] versus LIVY-xxx, as long as the integration scripts figure out things properly.

**Comment by jerryshao** [comment]
Thank @lresende , I just changed to use [LIVY-xxx] :)

**Pull request closed without merging**
