### PR TITLE
[LIVY-384] [Docs] Include local build of Docs

### PR DESCRIPTION
**Pull request by ajbozarth**
[LIVY-384](https://issues.cloudera.org/browse/LIVY-384)

Included a copy of the 0.4.0-incubating build of the Livy Docs in the website. The process for updating the Docs can be found in the Docs README in the main repo.

Paired with apache/incubator-livy#26

### CODE REVIEW

**Comment by ajbozarth** [comment]
Since we're planning to release 0.4.0 soon I think we should wait for the release and I will update this to include the released 0.4.0 Docs instead of the SNAPSHOT (pending no changes to apache/incubator-livy#26 before it's merged, the only updates needed would be to the directory name and symlink)

**Comment by ajbozarth** [comment]
Set to *WIP* so we don't merge this early

**Comment by jerryshao** [comment]
I will resolve LIVY-384, and this could be merged after LIVY 0.4 is out.

**Comment by ajbozarth** [comment]
Sounds like a plan, I'll remove the WIP so it's ready once 0.4 is out

**Comment by ajbozarth** [comment]
Note I will need to rebuild this before we merge because its still using 0.4.0-SNAPSHOT versioning, but I won't be able to do that until we have an rc1

**Comment by ajbozarth** [comment]
Updated based on rc1, with no change to the Docs during the rc process this will be good to merge once the release is finalized.

**Comment by ajbozarth** [comment]
FYI this is ready to go now that 0.4.0-incubating is out

**Comment by jerryshao** [comment]
Thanks @ajbozarth , let me merge it now.

**Pull request closed without merging**
