### PR TITLE
[Minor] Website Cleanup

### PR DESCRIPTION
**Pull request by ajbozarth**
Website cleanup split off of https://github.com/apache/incubator-livy-website/pull/5 for commit clarity

### CODE REVIEW

**Comment by ajbozarth** [comment]
@jerryshao mind merging this if you have no complaints?

**Comment by jerryshao** [comment]
OK, I will.

**Comment by jerryshao** [comment]
Would you please list the steps of how to use publish.sh, I'm still not clearly sure about it.

**Comment by ajbozarth** [comment]
If I understand correctly you should run it similar to your merge script. I don't know how the Apache process works since I've never had commit access though

**Comment by jerryshao** [comment]
Ok, let me take a try :p

**Comment by ajbozarth** [comment]
note: I'm pretty sure you have to merge the PR before running the script

**Comment by jerryshao** [comment]
Thanks! I'm working on Jekyll install, will merge after the environment is ready.

**Comment by jerryshao** [comment]
@ajbozarth I just pushed a commit to asf-site branch, would you please check if it is correct.

**Comment by ajbozarth** [comment]
perfect, website is up to date with the change

**Pull request closed without merging**
